dist: xenial

language: python

sudo: false

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"

matrix:
  include:
    - python: "pypy3"
      dist: trusty

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt

script:
  - python -m unittest discover -s tests -t tests

notifications:
  email: false
