dist: xenial
sudo: false

language: python
python:
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"
  - "pypy3.5"

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt

script:
  - pytest --cov=. --cov-report=term-missing

after_success:
  - coveralls

notifications:
  email: false
